const COUNTRY_TO_ISO: Record<string, string> = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Argentina: "AR",
  Armenia: "AM",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bangladesh: "BD",
  Belarus: "BY",
  Belgium: "BE",
  Bhutan: "BT",
  Bolivia: "BO",
  Brazil: "BR",
  Bulgaria: "BG",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  Congo: "CG",
  "Costa Rica": "CR",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Denmark: "DK",
  Ecuador: "EC",
  Egypt: "EG",
  Estonia: "EE",
  Ethiopia: "ET",
  Finland: "FI",
  France: "FR",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Guatemala: "GT",
  Haiti: "HT",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lithuania: "LT",
  Luxembourg: "LU",
  Madagascar: "MG",
  Malaysia: "MY",
  Maldives: "MV",
  Malta: "MT",
  Mauritius: "MU",
  Mexico: "MX",
  Moldova: "MD",
  Mongolia: "MN",
  Morocco: "MA",
  Myanmar: "MM",
  Nepal: "NP",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nigeria: "NG",
  "North Korea": "KP",
  "North Macedonia": "MK",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palestine: "PS",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  Qatar: "QA",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Singapore: "SG",
  Slovakia: "SK",
  Slovenia: "SI",
  "South Africa": "ZA",
  "South Korea": "KR",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  Taiwan: "TW",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  Turkmenistan: "TM",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Venezuela: "VE",
  Vietnam: "VN",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
  "Ivory Coast": "CI",
  "Democratic Republic of the Congo": "CD",
  "Republic of the Congo": "CG",
  "Timor-Leste": "TL",
  Brunei: "BN",
  Eswatini: "SZ",
  Lesotho: "LS",
  Namibia: "NA",
  Gabon: "GA",
  Djibouti: "DJ",
  Somalia: "SO",
  Guinea: "GN",
  "Sierra Leone": "SL",
  Liberia: "LR",
  "Burkina Faso": "BF",
  Mali: "ML",
  Niger: "NE",
  Chad: "TD",
  "Central African Republic": "CF",
  "Equatorial Guinea": "GQ",
  Gambia: "GM",
  "Guinea-Bissau": "GW",
  "Cape Verde": "CV",
  Comoros: "KM",
  Seychelles: "SC",
  Eritrea: "ER",
  Botswana: "BW",
  Mozambique: "MZ",
  Angola: "AO",
  Malawi: "MW",
  Togo: "TG",
  Benin: "BJ",
  Burundi: "BI",
  Mauritania: "MR",
  "Western Sahara": "EH",
  "Bosnia and Herzegovina": "BA",
  Montenegro: "ME",
  Kosovo: "XK",
  "South Sudan": "SS",
  "Puerto Rico": "PR",
  Guadeloupe: "GP",
  Martinique: "MQ",
  Reunion: "RE",
  Mayotte: "YT",
  "New Caledonia": "NC",
  "French Polynesia": "PF",
  Bermuda: "BM",
  "Cayman Islands": "KY",
  "British Virgin Islands": "VG",
  Guam: "GU",
  "American Samoa": "AS",
  Aruba: "AW",
  Curacao: "CW",
  "Sint Maarten": "SX",
  "Saint Martin": "MF",
  "Cook Islands": "CK",
  Niue: "NU",
  Tokelau: "TK",
  "Wallis and Futuna": "WF",
  "Saint Helena": "SH",
  "Tristan da Cunha": "TA",
};

export function getCountryFlag(country: string | null | undefined): string {
  if (!country) return "";
  const iso = COUNTRY_TO_ISO[country];
  if (!iso) return "";
  return `https://flagsapi.com/${iso}/flat/24.png`;
}

export function getCountryIso(country: string | null | undefined): string | null {
  if (!country) return null;
  return COUNTRY_TO_ISO[country] || null;
}
