/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        display: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        mono: ['"SF Mono"', '"SF Pro Mono"', '"JetBrains Mono"', 'Consolas', 'monospace'],
        "label-pill": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "metric-display": ["Plus Jakarta Sans"],
        "label-btn": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
      },
      colors: {
        primary: {
          DEFAULT: "#4f46e5",
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        "tertiary-container": "#acb9a6",
        "on-primary-container": "#3730a3",
        error: "#ba1a1a",
        "surface-variant": "#dce2f7",
        "surface-bright": "#f9f9ff",
        "on-error-container": "#93000a",
        tertiary: "#566252",
        "on-surface-variant": "#3f4a37",
        outline: "#6f7b65",
        "on-surface": "#141b2b",
        "surface-dim": "#d3daef",
        "tertiary-fixed-dim": "#becab7",
        "surface-container-low": "#f1f3ff",
        background: "#f9f9ff",
        "tertiary-fixed": "#d9e6d2",
        "surface-tint": "#286c00",
        "secondary-container": "#d6e3d6",
        "surface-container-high": "#e1e8fd",
        "on-primary": "#ffffff",
        "on-secondary-container": "#59665b",
        secondary: "#556157",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d9e6d8",
        "on-tertiary-container": "#3e4a3b",
        surface: "#f9f9ff",
        "primary-fixed-dim": "#69e02f",
        "on-tertiary-fixed-variant": "#3e4a3b",
        "primary-container": "#58ce18",
        "on-tertiary-fixed": "#141e12",
        "secondary-fixed-dim": "#bdcabd",
        "on-secondary-fixed-variant": "#3e4a40",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dce2f7",
        "surface-container": "#e9edff",
        "on-background": "#141b2b",
        "on-secondary-fixed": "#131e16",
        "on-secondary": "#ffffff",
        "primary-fixed": "#85fe4b",
        "on-error": "#ffffff",
        "inverse-surface": "#293040",
        "on-primary-fixed": "#072100",
        "outline-variant": "#becbb2",
        "on-primary-fixed-variant": "#1c5200",
        "inverse-primary": "#69e02f",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#edf0ff",
      },
      fontSize: {
        "label-pill": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "800" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "metric-display": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-btn": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        'card-hover': '0 4px 12px 0 rgb(0 0 0 / 0.08), 0 2px 4px -1px rgb(0 0 0 / 0.04)',
        dropdown: '0 10px 25px -3px rgb(0 0 0 / 0.1), 0 4px 8px -2px rgb(0 0 0 / 0.06)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.2s ease-out',
        'pulse-soft': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};