import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ALL_PERMISSIONS = [
  "dashboard:view",
  "dashboard:export",
  "universities:read",
  "universities:create",
  "universities:update",
  "universities:delete",
  "universities:export",
  "universities:import",
  "universities:partners",
  "courses:read",
  "courses:create",
  "courses:update",
  "courses:delete",
  "courses:export",
  "courses:import",
  "students:read",
  "students:create",
  "students:update",
  "students:delete",
  "students:export",
  "students:import",
  "students:credentials",
  "students:messages",
  "applications:read",
  "applications:create",
  "applications:update",
  "applications:delete",
  "applications:export",
  "applications:workflow",
  "leads:read",
  "leads:create",
  "leads:update",
  "leads:delete",
  "leads:export",
  "leads:assign",
  "payments:read",
  "payments:create",
  "payments:update",
  "payments:delete",
  "payments:export",
  "payments:refund",
  "expenses:read",
  "expenses:create",
  "expenses:update",
  "expenses:delete",
  "expenses:export",
  "reports:read",
  "reports:create",
  "reports:delete",
  "analytics:read",
  "analytics:export",
  "hr:read",
  "hr:create",
  "hr:update",
  "hr:delete",
  "hr:attendance",
  "hr:leave",
  "hr:payroll",
  "hr:export",
  "files:read",
  "files:create",
  "files:update",
  "files:delete",
  "files:share",
  "calendar:read",
  "calendar:create",
  "calendar:update",
  "calendar:delete",
  "visa:read",
  "visa:create",
  "visa:update",
  "visa:delete",
  "workflow:read",
  "workflow:create",
  "workflow:update",
  "workflow:delete",
  "users:read",
  "users:create",
  "users:update",
  "users:delete",
  "roles:read",
  "roles:create",
  "roles:update",
  "roles:delete",
  "permissions:read",
  "permissions:update",
  "api_keys:read",
  "api_keys:create",
  "api_keys:delete",
  "settings:read",
  "settings:update",
  "backups:read",
  "backups:create",
  "backups:restore",
  "branches:read",
  "branches:create",
  "branches:update",
  "branches:delete",
  "chat:read",
  "chat:send",
  "email:read",
  "email:create",
  "email:update",
  "email:delete",
  "notifications:read",
  "notifications:create",
  "notifications:update",
  "notifications:delete",
  "tasks:read",
  "tasks:create",
  "tasks:update",
  "tasks:delete",
  "learning:read",
  "learning:create",
  "learning:update",
  "learning:delete",
  "automations:read",
  "automations:create",
  "automations:update",
  "automations:delete",
  "marketing:read",
  "marketing:create",
  "marketing:update",
  "marketing:delete",
  "audit:read",
  "audit:export",
  "trash:read",
  "trash:restore",
  "trash:delete",
  "bulk:import",
  "bulk:export",
  "qualifications:read",
  "qualifications:create",
  "qualifications:update",
  "qualifications:delete",
  "compare:read",
  "compare:create",
  "compare:update",
  "compare:delete",
  "onboarding:read",
  "onboarding:create",
  "onboarding:update",
  "onboarding:delete",
];

const INITIAL_ROLES = [
  {
    name: "Super Admin",
    description: "Super administrator with unrestricted system-wide access.",
    permissions: JSON.stringify(ALL_PERMISSIONS),
    color: "text-violet-600 bg-violet-50 border-violet-200",
  },
  {
    name: "Administrator",
    description: "Full access to all modules and settings.",
    permissions: JSON.stringify(ALL_PERMISSIONS),
    color: "text-rose-600 bg-rose-50 border-rose-200",
  },
  {
    name: "Moderator",
    description: "Can manage courses and universities but cannot edit system settings.",
    permissions: JSON.stringify([
      "dashboard:view",
      "universities:read",
      "universities:create",
      "universities:update",
      "universities:export",
      "universities:import",
      "courses:read",
      "courses:create",
      "courses:update",
      "courses:export",
      "courses:import",
      "students:read",
      "applications:read",
      "leads:read",
      "reports:read",
      "analytics:read",
      "files:read",
      "calendar:read",
      "visa:read",
      "workflow:read",
      "settings:read",
    ]),
    color: "text-indigo-600 bg-indigo-50 border-indigo-200",
  },
  {
    name: "Editor",
    description: "Can edit content but cannot approve or delete.",
    permissions: JSON.stringify([
      "dashboard:view",
      "universities:read",
      "universities:update",
      "courses:read",
      "courses:update",
      "students:read",
      "students:update",
      "applications:read",
      "applications:update",
      "reports:read",
      "analytics:read",
      "files:read",
      "settings:read",
    ]),
    color: "text-emerald-600 bg-emerald-50 border-emerald-200",
  },
  {
    name: "Viewer",
    description: "Read-only access to all modules.",
    permissions: JSON.stringify([
      "dashboard:view",
      "universities:read",
      "courses:read",
      "students:read",
      "applications:read",
      "reports:read",
      "analytics:read",
      "files:read",
      "calendar:read",
      "settings:read",
    ]),
    color: "text-slate-600 bg-slate-50 border-slate-200",
  },
  {
    name: "B2B Partner",
    description:
      "B2B recruitment partner — views partnerships, commissions, universities, and referred students.",
    permissions: JSON.stringify([
      "dashboard:view",
      "universities:read",
      "universities:update",
      "courses:read",
      "courses:update",
      "students:read",
      "applications:read",
      "reports:read",
      "analytics:read",
      "files:read",
      "calendar:read",
      "settings:read",
    ]),
    color: "text-cyan-600 bg-cyan-50 border-cyan-200",
  },
  {
    name: "Student",
    description: "Student portal access — can view own applications, payments, and documents.",
    permissions: JSON.stringify([]),
    color: "text-amber-600 bg-amber-50 border-amber-200",
  },
];

async function main() {
  console.log("Seeding roles...");
  await Promise.all(
    INITIAL_ROLES.map((role) =>
      prisma.role.upsert({
        where: { name: role.name },
        update: {
          description: role.description,
          permissions: role.permissions,
          color: role.color,
        },
        create: role,
      })
    )
  );
  console.log("Roles seeded successfully.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });